dev-deployment:
 variables:
   GIT_STRATEGY: fetch
 script:
   - bash ~/gitlab/NextJS/nextjs-projectdeploy-yarn-v1.sh
 environment:
     name: Development
     url : https://ryken-admin.dedicateddevelopers.us/
 tags:
   -  dev-runner
 only:
   - dev
